---
title: "DataAnalysis - Postprocessing Results MaxQuant"
autor: David Lilek
date: "`r format(Sys.time(), '%d %B %Y, %X')`"
output:
  html_document:
    df_print: paged
    fig.align: center
    self_contained: yes
    fig.height: 4
    fig.width: 8
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
    code_folding: hide
---

```{r start, message=FALSE, warning=FALSE, include=FALSE}
start_time = format(Sys.time(), '%X')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
#load libraries
library(tidyverse)
library(dplyr)
library(gplots)
library(reshape2) #for melting data for boxplot with ggplot
library(pheatmap)
library(MASS)
library(ggpubr)
library(kableExtra)
```


```{r results="asis"}
###############################
#
#define settings
#
###############################

path = "N:/1_A_Bachelor_Master_Intern/00_M_2022/David/Data/evaluation_masterthesis/UPS1/tmpfiles/UPS1_twouniquepeptides_human/"

##########read in all data with pattern .txt
# get file list
file.list <- list.files(path = path, pattern='*.csv')
# create file path
file.path <- paste(path,file.list,sep = "")
# read in files - for each file one variable is created - results are stored in a list
res_raw <- lapply(file.path, function(i){read.csv2(i, row.names = 1)})
names(res_raw) <- file.list
```

```{r}
#create data.frame
res<-as.data.frame(res_raw)
rownames(res) <- NULL
```

```{r}
#functions
CV <- function(x){
  (sd(x)/mean(x))*100
}

MEAN <- function(x){
  mean(x)
}
```


```{r}
#set sample name
sample_names <- c("10fmol","25fmol","2fmol","4fmol","50fmol")
col_names <- c("MBR_pooled","MBR_pooled\noldversion","noMBR_pooled","noMBR_pooled\noldversion")
#col_names <- c("MBR_pooled","MBR_pooled\noldversion","MBR","noMBR_pooled","noMBR_pooled\noldversion","noMBR")
```


```{r, results="asis"}
no <- c()
rsd <- c()
type <- c()
evaluation <- c()
conc <- c()

for (sample_name in sample_names){
  #razor
  razor <- res %>%
    dplyr::select(ends_with(sample_name) & contains("Razor"))
  colnames(razor) <- col_names

  #unique
  unique <- res %>%
  dplyr::select(ends_with(sample_name) & contains("Unique"))
  colnames(unique) <- col_names

  #lfq
  lfq <- res %>%
  dplyr::select(ends_with(sample_name) & contains("LFQ"))
  colnames(lfq) <- col_names

  #plot data
  no <- c(no, c(apply(razor,2,MEAN),apply(unique,2,MEAN),apply(lfq,2,MEAN)))
  no <- round(no,1)
  rsd <- c(rsd, c(apply(razor,2,CV),apply(unique,2,CV),apply(lfq,2,CV)))
  rsd <- round(rsd,3)
  
  evaluation <- c(evaluation, rep(col_names,3))
  type <- c(type, rep(c("Razor","Unique","LFQ"), each=length(file.list)))
}
 
```

```{r}
conc <- rep(c(10,25,2,4,50), each = 12)
res_human <- data.frame(no,rsd,evaluation,type,conc)

ggplot(data=res_human, aes(x=conc, y=no, color = evaluation, linetype = type)) +
  geom_line() +
  geom_point() + 
  ylab("Number of Proteins") + 
  xlab("Concentration [fmol]") +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())

```

