---
title: "DataAnalysis - Extracts Sequence 20220609 - UniProtR"
autor: David Lilek
date: "`r format(Sys.time(), '%d %B %Y, %X')`"
output:
  html_document:
    df_print: paged
    fig.align: center
    self_contained: yes
    fig.height: 4
    fig.width: 8
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
    code_folding: hide
---

# Get protein functions for proteins

* Functions are shortened in the plots because  they are quite long
* a table with the whole function name is provided after each plot

```{r message=FALSE, warning=FALSE}
library(reshape)
library(ggplot2)
library(dplyr)
library(knitr)
library(UniprotR)
GO <- readRDS("GO.rds")
#GeneOntologyObj$Gene.ontology..biological.process.
#GeneOntologyObj$Gene.ontology..molecular.function.
#GeneOntologyObj$Gene.ontology..cellular.component

################################# Biological process

t_BP <- as.data.frame(table(GO[[1]]$Gene.ontology..biological.process.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_1 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[2]]$Gene.ontology..biological.process.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_2 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[3]]$Gene.ontology..biological.process.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_3 <- t_BP_sorted[c(1:10),]

BP <- merge(t_BP_sorted_1, t_BP_sorted_2,
            all = TRUE,
            by = "Var1")

BP <- merge(BP, t_BP_sorted_3,
            all = TRUE,
            by = "Var1")

colnames(BP) <- c("Function", "Pool", "B&Pool", "B")

BP_4ggplot <- melt(BP)

BP_4ggplot$Function_short <- substr(BP_4ggplot$Function,1,15)

ggplot(BP_4ggplot, aes(x=Function_short, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  theme_minimal() +
  scale_fill_brewer(palette="Dark2") +
  theme(legend.position="bottom") +
  theme(legend.key.size = unit(0.15, 'cm')) +
  guides(fill=guide_legend(nrow=2, byrow=TRUE)) +
  ylab("Counts") +
  labs(fill = "Proteins") +
  ggtitle("Biological processes") +
  coord_flip()
#theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size =8))+
kable(BP_4ggplot$Function)

################################# Molecular Function

t_BP <- as.data.frame(table(GO[[1]]$Gene.ontology..molecular.function.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_1 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[2]]$Gene.ontology..molecular.function.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_2 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[3]]$Gene.ontology..molecular.function.))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_3 <- t_BP_sorted[c(1:10),]

BP <- merge(t_BP_sorted_1, t_BP_sorted_2,
            all = TRUE,
            by = "Var1")

BP <- merge(BP, t_BP_sorted_3,
            all = TRUE,
            by = "Var1")

colnames(BP) <- c("Function", "Pool", "B&Pool", "B")

BP_4ggplot <- melt(BP)

BP_4ggplot$Function_short <- substr(BP_4ggplot$Function,1,15)

ggplot(BP_4ggplot, aes(x=Function_short, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  theme_minimal() +
  scale_fill_brewer(palette="Dark2") +
  theme(legend.position="bottom") +
  theme(legend.key.size = unit(0.15, 'cm')) +
  guides(fill=guide_legend(nrow=2, byrow=TRUE)) +
  ylab("Counts") +
  labs(fill = "Proteins") +
  ggtitle("Molecular Function")+
  coord_flip()
kable(BP_4ggplot$Function)
################################# Cellular component

t_BP <- as.data.frame(table(GO[[1]]$Gene.ontology..cellular.component))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_1 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[2]]$Gene.ontology..cellular.component))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_2 <- t_BP_sorted[c(1:10),]
t_BP <- as.data.frame(table(GO[[3]]$Gene.ontology..cellular.component))
t_BP_sorted <- arrange(t_BP, desc(Freq))
t_BP_sorted_3 <- t_BP_sorted[c(1:10),]

BP <- merge(t_BP_sorted_1, t_BP_sorted_2,
            all = TRUE,
            by = "Var1")

BP <- merge(BP, t_BP_sorted_3,
            all = TRUE,
            by = "Var1")

colnames(BP) <- c("Function", "Pool", "B&Pool", "B")

BP_4ggplot <- melt(BP)

BP_4ggplot$Function_short <- substr(BP_4ggplot$Function,1,15)

ggplot(BP_4ggplot, aes(x=Function_short, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  theme_minimal() +
  scale_fill_brewer(palette="Dark2") +
  theme(legend.position="bottom") +
  theme(legend.key.size = unit(0.15, 'cm')) +
  guides(fill=guide_legend(nrow=2, byrow=TRUE)) +
  ylab("Counts") +
  labs(fill = "Proteins") +
  ggtitle("Cellular component")+
  coord_flip()
kable(BP_4ggplot$Function)
```

# KEGG and other stuff

```{r message=FALSE, warning=FALSE}
fasta <- read.csv("fasta.csv", header = F)

Enrichment.KEGG(fasta$V1, OS="tcastaneum")
Enrichment.MF(fasta$V1, OS="tcastaneum")
```

